name: "Release"
description: "Tag & Push to Production"
author: "eng-utc@untappd.com"

inputs:
  tag_name:
    description: "Tag Name, defaults to YYYY.MM.DD.hhmmss UTC"
    required: false
  github_token:
    description: "GH token for performing actions against the repo"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "upload-cloud"
  color: "yellow"