name: 'Release'

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  merge-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: untappd/utc-release-action@master
        name: Tag & Push Rebase to Production
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
